server:
  port: 18081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/skilltrackv1

logging:
  level:
    com.skilltrack: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
  instance:
    prefer-ip-address: true
